//LOGIN ACTION
export const LOGIN_ACTION = 'LOGIN_ACTION'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

//ADD BREEDING
export const ADD_BREEDING_ACTION = 'ADD_BREEDING_ACTION'
export const ADD_BREEDING_SUCCESS = 'ADD_BREEDING_SUCCESS'
export const ADD_BREEDING_FAIL = 'ADD_BREEDING_FAIL'

//ADD POPULATION
export const ADD_POPULATION_ACTION = 'ADD_POPULATION_ACTION'
export const ADD_POPULATION_SUCCESS = 'ADD_POPULATION_SUCCESS'
export const ADD_POPULATION_FAIL = 'ADD_POPULATION_FAIL'

//ADD MEDICATION
export const ADD_MEDICATION_ACTION = 'ADD_MEDICATION_ACTION'
export const ADD_MEDICATION_SUCCESS = 'ADD_MEDICATION_SUCCESS'
export const ADD_MEDICATION_FAIL = 'ADD_MEDICATION_FAIL'

//ADD BOOK KEEPING
export const ADD_BOOK_KEEPING_ACTION = 'ADD_BOOK_KEEPING_ACTION'
export const ADD_BOOK_KEEPING_SUCCESS = 'ADD_BOOK_KEEPING_SUCCESS'
export const ADD_BOOK_KEEPING_FAIL = 'ADD_BOOK_KEEPING_FAIL'

//GET BREEDING
export const GET_BREEDING_ACTION = 'GET_BREEDING_ACTION'
export const GET_BREEDING_SUCCESS = 'GET_BREEDING_SUCCESS'
export const GET_BREEDING_FAIL = 'GET_BREEDING_FAIL'

//GET POPULATION
export const GET_POPULATION_ACTION = 'GET_POPULATION_ACTION'
export const GET_POPULATION_SUCCESS = 'GET_POPULATION_SUCCESS'
export const GET_POPULATION_FAIL = 'GET_POPULATION_FAIL'

//GET BOOK KEEPING
export const GET_BOOK_KEEPING_ACTION = 'GET_BOOK_KEEPING_ACTION'
export const GET_BOOK_KEEPING_SUCCESS = 'GET_BOOK_KEEPING_SUCCESS'
export const GET_BOOK_KEEPING_FAIL = 'GET_BOOK_KEEPING_FAIL'

//GET MEDICATION
export const GET_MEDICATION_ACTION = 'GET_MEDICATION_ACTION'


//GET KINDLINGBOX NOTIFICATIONS
export const GET_KINDLINGBOX_SUCCESS = 'GET_KINDLINGBOX_SUCCESS'

//GET WEANINGDATE NOTIFICATIONS
export const GET_WEANINGDATE_SUCCESS = 'GET_WEANINGDATE_SUCCESS'

//GET NEXTBREEDINGDATE NOTIFICATIONS
export const GET_NEXTBREEDINGDATE_SUCCESS = 'GET_NEXTBREEDINGDATE_SUCCESS'